#!/bin/sh

PROBLEM_NUMBERS=$(for i in problems/*.txt; do echo $(basename $i .txt); done|sort -g)

for i in $PROBLEM_NUMBERS; do 
  PROBLEM=$i
  SOLUTION=problems/bbrects/$PROBLEM.txt
  curl --compressed -L -H Expect: -H 'X-API-Key: 41-736c4fa841ea2c5e62c5991086b87886' -F "problem_id=$PROBLEM" -F "solution_spec=@$SOLUTION" 'http://2016sv.icfpcontest.org/api/solution/submit' > submits/bbrects/$PROBLEM.txt
  echo ""
  sleep 1.5
done
